name: portfolio-deployment

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    pages: write
    id-token: write
    contents: read
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              run: echo "Hello worlds"